#!/usr/bin/env node
/* eslint-disable no-console */
const fs = require('fs')
const path = require('path')
const { execSync } = require('child_process')

function getCommit() {
  const envKeys = [
    'VITE_COMMIT',
    'NEXT_PUBLIC_COMMIT',
    'GITHUB_SHA',
    'VERCEL_GIT_COMMIT_SHA',
    'COMMIT_SHA',
    'SOURCE_VERSION'
  ]
  for (const k of envKeys) {
    if (process.env[k]) return String(process.env[k])
  }
  try {
    const sha = execSync('git rev-parse HEAD', { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim()
    return sha
  } catch (_) {
    return 'dev'
  }
}

const commit = getCommit()
const short = commit.slice(0, 7)

const outPath = path.join(__dirname, '..', 'src', 'lib', 'commit.ts')
const content = `// Auto-generated by scripts/write-commit.js\nexport const PKG_COMMIT = '${short}'\n`

fs.writeFileSync(outPath, content)
console.log(`[build] wrote commit ${short} to src/lib/commit.ts`)


